### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Cryptonic-zz** [DomBlack/php-scrypt#5]
Attempted to compile on Freebsd 9 with GCC4.7, resulted in the following errors:

/php-scrypt/php_scrypt.c:45:1: error: unknown type name 'function_entry'
/php-scrypt/php_scrypt.c:46:5: warning: braces around scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: initialization makes integer from pointer without a cast [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:46:5: error: initializer element is not computable at load time
/php-scrypt/php_scrypt.c:46:5: error: (near initialization for 'scrypt_functions[0]')
/php-scrypt/php_scrypt.c:46:5: warning: excess elements in scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: excess elements in scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: excess elements in scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: excess elements in scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:46:5: warning: (near initialization for 'scrypt_functions[0]') [enabled by default]
/php-scrypt/php_scrypt.c:47:5: warning: braces around scalar initializer [enabled by default]
/php-scrypt/php_scrypt.c:47:5: warning: (near initialization for 'scrypt_functions[1]') [enabled by default]
/php-scrypt/php_scrypt.c:47:5: warning: initialization makes integer from pointer without a cast [enabled by default]
